spin_manifest_version = "1"
authors = ["Rajat Jindal <rajatjindal83@gmail.com>"]
description = ""
name = "bluesky-id"
trigger = { type = "http", base = "/" }
version = "0.1.0"

[[component]]
id = "bluesky-id"
source = "main.wasm"
allowed_http_hosts = ["bsky.social"]
key_value_stores = ["default"]
[component.trigger]
route = "/api/..."
[component.build]
command = "tinygo build -target=wasi -gc=leaking -no-debug -o main.wasm main.go"
watch = ["main.go", "go.mod"]

[[component]]
source = "spin_static_fs.wasm"
id = "fileserver_static"
files = [ { source = "frontend/", destination = "/" } ]
[component.trigger]
route = "/..."
[component.build]
command = ""
watch = ["frontend/**/*"]
